name: lambda_github_action_test_deploy deploy 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          tag: v0.14.0 # Remove this if you want to grab always the latest version
          platform: linux # Other valid options: 'windows' or 'darwin'
          arch: x86_64 # Other valid options for linux: 'aarch64'
      # Add your build steps below
      - name: release-build
        working-directory: ./app
        run: |
          cargo lambda build --release
          ls target/lambda
      
      - name: release-deploy
      #working-directoryでディレクトリの指定ができるらしい。（https://stackoverflow.com/questions/58139175/running-actions-in-another-directory）
        working-directory: app
        run: |
          cargo lambda deploy --binary-name app lambda_github_action_test --iam-role ${{ secrets.LAMBDA_IAM_ROLE }}
